repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: master
    hooks:
      - id: go-build-repo
      - id: go-test-repo
      - id: go-staticcheck-repo
      - id: go-fmt
      - id: go-fumpt
      - id: go-imports
      - id: go-lint
      - id: golangci-lint-mod
        args: [-c.golang-ci.yml]