# Goreleaer does not support multi staged builds: https://github.com/goreleaser/goreleaser/issues/609#issuecomment-534748384
FROM gcr.io/distroless/static-debian12@sha256:87bce11be0af225e4ca761c40babb06d6d559f5767fbf7dc3c47f0f1a466b92c
WORKDIR /
COPY vault-kubernetes-kms .

ENTRYPOINT ["/vault-kubernetes-kms"]
