# Goreleaer does not support multi staged builds: https://github.com/goreleaser/goreleaser/issues/609#issuecomment-534748384
FROM gcr.io/distroless/static-debian12@sha256:69830f29ed7545c762777507426a412f97dad3d8d32bae3e74ad3fb6160917ea
WORKDIR /
COPY vault-kubernetes-kms .

ENTRYPOINT ["/vault-kubernetes-kms"]
