site_name: vault-kms-plugin
site_description: "Encrypt Kubernetes Secrets using Hashicorp Vault as the KMS Provider"
site_author: FalcoSuessgott

repo_name: FalcoSuessgott/vault-kms-plugin
repo_url: https://github.com/FalcoSuessgott/vault-kubernetes-kms

docs_dir: docs/

plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      locale: en
      enable_creation_date: false

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - toc:
      permalink: true
  - markdown_include.include:
        base_path: docs

nav:
  - vault-kubernetes-kms:
    - index.md
    - quickstart.md
    - configuration.md
    - concepts.md
    - sign.md
    - metrics.md
    - integration.md
    - troubleshooting.md
    - development.md
theme:
  icon:
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/github
  name: material

  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/eye
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.action.edit
    - navigation.top
    - navigation.expand
    - navigation.footer
