package testutils

import (
	"bytes"
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"errors"
	"fmt"
	"io"
	"math/big"
	"net"
	"os"
	"strings"
	"time"

	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"
)

// vaultTLSConfig is the Vault HCL config for a TLS-enabled non-dev instance.
const vaultTLSConfig = `
storage "inmem" {}

listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_cert_file = "/tmp/vault-server.crt"
  tls_key_file  = "/tmp/vault-server.key"
}

disable_mlock = true
api_addr      = "https://0.0.0.0:8200"
`

// TLSCerts holds PEM-encoded ephemeral certs generated by GenerateTestCerts.
type TLSCerts struct {
	CACertPEM     []byte
	ServerCertPEM []byte
	ServerKeyPEM  []byte
	ClientCertPEM []byte
	ClientKeyPEM  []byte
}

// TLSTestContainer wraps a non-dev Vault container running with TLS enabled.
// CACertFile, ClientCertFile, and ClientKeyFile are host-side paths for use with
// the Vault SDK's api.TLSConfig.
type TLSTestContainer struct {
	*TestContainer

	CACertFile     string
	ClientCertFile string
	ClientKeyFile  string

	cleanup func()
}

// Terminate stops the container and removes temp host-side cert files.
func (v *TLSTestContainer) Terminate() error {
	if v.cleanup != nil {
		v.cleanup()
	}

	return v.TestContainer.Terminate()
}

// ExecWithToken runs a vault CLI command inside the container with VAULT_TOKEN pre-set.
func (v *TLSTestContainer) ExecWithToken(cmd string) (string, error) {
	return tlsExecAndRead(context.Background(), v.Container,
		"sh", "-c", fmt.Sprintf("VAULT_TOKEN=%s %s", v.Token, cmd))
}

// GenerateTestCerts creates an ephemeral CA, server cert (for Vault HTTPS), and client cert
// (for Vault cert auth). All three are signed by the same CA.
//
//nolint:funlen,mnd
func GenerateTestCerts() (*TLSCerts, error) {
	caKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("generate CA key: %w", err)
	}

	caTemplate := &x509.Certificate{
		SerialNumber:          big.NewInt(1),
		Subject:               pkix.Name{CommonName: "Vault Test CA"},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().Add(24 * time.Hour),
		IsCA:                  true,
		BasicConstraintsValid: true,
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
	}

	caCertDER, err := x509.CreateCertificate(rand.Reader, caTemplate, caTemplate, &caKey.PublicKey, caKey)
	if err != nil {
		return nil, fmt.Errorf("create CA cert: %w", err)
	}

	caCert, err := x509.ParseCertificate(caCertDER)
	if err != nil {
		return nil, fmt.Errorf("parse CA cert: %w", err)
	}

	// Server cert — SANs cover localhost and 127.0.0.1 so the SDK can verify it.
	serverKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("generate server key: %w", err)
	}

	serverTemplate := &x509.Certificate{
		SerialNumber: big.NewInt(2),
		Subject:      pkix.Name{CommonName: "vault-server"},
		DNSNames:     []string{"localhost"},
		IPAddresses:  []net.IP{net.IPv4(127, 0, 0, 1)},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().Add(24 * time.Hour),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}

	serverCertDER, err := x509.CreateCertificate(rand.Reader, serverTemplate, caCert, &serverKey.PublicKey, caKey)
	if err != nil {
		return nil, fmt.Errorf("create server cert: %w", err)
	}

	// Client cert for Vault cert auth.
	clientKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("generate client key: %w", err)
	}

	clientTemplate := &x509.Certificate{
		SerialNumber: big.NewInt(3),
		Subject:      pkix.Name{CommonName: "vault-client"},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().Add(24 * time.Hour),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageClientAuth},
	}

	clientCertDER, err := x509.CreateCertificate(rand.Reader, clientTemplate, caCert, &clientKey.PublicKey, caKey)
	if err != nil {
		return nil, fmt.Errorf("create client cert: %w", err)
	}

	certs := &TLSCerts{
		CACertPEM:     pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: caCertDER}),
		ServerCertPEM: pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: serverCertDER}),
		ClientCertPEM: pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: clientCertDER}),
	}

	serverKeyBytes, err := x509.MarshalECPrivateKey(serverKey)
	if err != nil {
		return nil, fmt.Errorf("marshal server key: %w", err)
	}

	certs.ServerKeyPEM = pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: serverKeyBytes})

	clientKeyBytes, err := x509.MarshalECPrivateKey(clientKey)
	if err != nil {
		return nil, fmt.Errorf("marshal client key: %w", err)
	}

	certs.ClientKeyPEM = pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: clientKeyBytes})

	return certs, nil
}

// StartTLSTestContainer starts a Vault container with TLS enabled (non-dev mode).
// Vault is initialized (1-of-1 unseal) and unsealed automatically. The root token
// is stored in TestContainer.Token. Use ExecWithToken for further vault CLI setup.
//
//nolint:cyclop,funlen,mnd
func StartTLSTestContainer(certs *TLSCerts) (*TLSTestContainer, error) {
	// Host-side temp files are only needed for the SDK client (CA cert, client cert/key).
	// Server cert and config are passed in-memory via ContainerRequest.Files.
	caCertFile, err := writeTLSTempFile("vault-ca-cert-*.pem", certs.CACertPEM)
	if err != nil {
		return nil, err
	}

	clientCertFile, err := writeTLSTempFile("vault-client-cert-*.pem", certs.ClientCertPEM)
	if err != nil {
		os.Remove(caCertFile)

		return nil, err
	}

	clientKeyFile, err := writeTLSTempFile("vault-client-key-*.pem", certs.ClientKeyPEM)
	if err != nil {
		os.Remove(caCertFile)
		os.Remove(clientCertFile)

		return nil, err
	}

	cleanupFiles := func() {
		os.Remove(caCertFile)
		os.Remove(clientCertFile)
		os.Remove(clientKeyFile)
	}

	ctx := context.Background()

	req := testcontainers.GenericContainerRequest{
		ContainerRequest: testcontainers.ContainerRequest{
			Image:        image,
			ExposedPorts: []string{"8200/tcp"},
			Cmd:          []string{"vault", "server", "-config=/tmp/vault-config.hcl"},
			Env: map[string]string{
				"VAULT_SKIP_VERIFY": "true",
				"VAULT_ADDR":        "https://127.0.0.1:8200",
			},
			// Files are copied to the container before it starts, so Vault has them at startup.
			// All files use 0o444 — Vault runs as a non-root user inside the container and the
			// files are owned by root after docker cp, so owner-only modes would be unreadable.
			Files: []testcontainers.ContainerFile{
				{
					Reader:            bytes.NewReader(certs.ServerCertPEM),
					ContainerFilePath: "/tmp/vault-server.crt",
					FileMode:          0o444,
				},
				{
					Reader:            bytes.NewReader(certs.ServerKeyPEM),
					ContainerFilePath: "/tmp/vault-server.key",
					FileMode:          0o444,
				},
				{
					Reader:            bytes.NewReader([]byte(vaultTLSConfig)),
					ContainerFilePath: "/tmp/vault-config.hcl",
					FileMode:          0o444,
				},
			},
			WaitingFor: wait.ForListeningPort("8200/tcp").WithStartupTimeout(30 * time.Second),
		},
		Started: true,
	}

	container, err := testcontainers.GenericContainer(ctx, req)
	if err != nil {
		cleanupFiles()

		return nil, fmt.Errorf("start TLS vault container: %w", err)
	}

	// Brief pause to let Vault finish binding before we exec init.
	time.Sleep(500 * time.Millisecond)

	initOutput, err := tlsExecAndRead(ctx, container,
		"vault", "operator", "init",
		"-key-shares=1", "-key-threshold=1",
		"-format=json",
	)
	if err != nil {
		container.Terminate(ctx) //nolint:errcheck
		cleanupFiles()
		return nil, fmt.Errorf("vault init: %w", err)
	}

	rootToken, unsealKey, err := parseVaultInitOutput(initOutput)
	if err != nil {
		container.Terminate(ctx) //nolint:errcheck
		cleanupFiles()
		return nil, fmt.Errorf("parse vault init output: %w (raw: %q)", err, initOutput)
	}

	_, err = tlsExecAndRead(ctx, container, "vault", "operator", "unseal", unsealKey)
	if err != nil {
		container.Terminate(ctx) //nolint:errcheck
		cleanupFiles()
		return nil, fmt.Errorf("vault unseal: %w", err)
	}

	host, err := container.Host(ctx)
	if err != nil {
		container.Terminate(ctx) //nolint:errcheck
		cleanupFiles()
		return nil, fmt.Errorf("get container host: %w", err)
	}

	port, err := container.MappedPort(ctx, "8200/tcp")
	if err != nil {
		container.Terminate(ctx) //nolint:errcheck
		cleanupFiles()
		return nil, fmt.Errorf("get container port: %w", err)
	}

	return &TLSTestContainer{
		TestContainer: &TestContainer{
			Container: container,
			URI:       "https://" + net.JoinHostPort(host, port.Port()),
			Token:     rootToken,
		},
		CACertFile:     caCertFile,
		ClientCertFile: clientCertFile,
		ClientKeyFile:  clientKeyFile,
		cleanup:        cleanupFiles,
	}, nil
}

// parseVaultInitOutput extracts root_token and first unseal key from vault operator init JSON.
// It uses simple string scanning rather than encoding/json to avoid import complexity and
// handles both compact (`"key":"value"`) and spaced (`"key": "value"`) JSON formatting.
func parseVaultInitOutput(raw string) (string, string, error) {
	raw = strings.TrimSpace(raw)

	rootToken, err := extractJSONString(raw, `"root_token"`)
	if err != nil {
		return "", "", fmt.Errorf("root_token: %w", err)
	}

	// unseal_keys_b64 is an array; find the bracket, then the first quoted value.
	const ukKey = `"unseal_keys_b64"` //nolint:gosec

	_, rest, found := strings.Cut(raw, ukKey)
	if !found {
		return "", "", errors.New("unseal_keys_b64 not found")
	}

	bracketIdx := strings.Index(rest, "[")
	if bracketIdx < 0 {
		return "", "", errors.New("malformed unseal_keys_b64: missing array bracket")
	}

	rest = rest[bracketIdx:]

	unsealKey, err := extractJSONString(rest, "")
	if err != nil {
		return "", "", fmt.Errorf("unseal_keys_b64 value: %w", err)
	}

	return rootToken, unsealKey, nil
}

// extractJSONString finds the first quoted string value after key in s.
// If key is empty, it finds the first quoted value in s directly.
func extractJSONString(s, key string) (string, error) {
	if key != "" {
		idx := strings.Index(s, key)
		if idx < 0 {
			return "", fmt.Errorf("%s not found", key)
		}

		s = s[idx+len(key):]
	}

	openIdx := strings.Index(s, `"`)
	if openIdx < 0 {
		return "", errors.New("no opening quote found")
	}

	s = s[openIdx+1:]

	value, _, found := strings.Cut(s, `"`)
	if !found {
		return "", errors.New("no closing quote found")
	}

	return value, nil
}

func tlsExecAndRead(ctx context.Context, c testcontainers.Container, args ...string) (string, error) {
	_, r, err := c.Exec(ctx, args)
	if err != nil {
		return "", err
	}

	out, err := io.ReadAll(r)
	if err != nil {
		return "", err
	}

	// Docker exec output has an 8-byte multiplexed stream header per frame.
	if len(out) > 8 { //nolint:mnd
		out = out[8:]
	}

	return string(out), nil
}

func writeTLSTempFile(pattern string, data []byte) (string, error) {
	f, err := os.CreateTemp("", pattern)
	if err != nil {
		return "", fmt.Errorf("create temp file %s: %w", pattern, err)
	}

	defer f.Close()

	_, err = f.Write(data)
	if err != nil {
		os.Remove(f.Name())
		return "", fmt.Errorf("write temp file %s: %w", pattern, err)
	}

	return f.Name(), nil
}
