apiVersion: v1
kind: Service
metadata:
  name: vault-kubernetes-kms
  namespace: kube-system
spec:
  selector:
    app: vault-kubernetes-kms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
