apiVersion: v1
kind: Pod
metadata:
  name: vault-kubernetes-kms
  namespace: kube-system
spec:
  containers:
    - name: vault-kubernetes-kms
      image: vault-kubernetes-kms
      imagePullPolicy: Never
      command:
        - vault-kubernetes-kms
        - --vault-address=http://host.minikube.internal:8200
        # token auth
        #- --vault-token=root
        # k8s auth
        - --vault-k8s-role=kms
      volumeMounts:
        - name: socket
          mountPath: /opt
  volumes:
    - name: socket
      hostPath:
        path: /opt