name: Lint Commit Messages

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  commitlint:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
