name: Lint Commit Messages
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  commitlint:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5