name: Test and coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.1'
          cache: false

      - run: go generate -tags tools tools/tools.go

      - name: go get
        run: go get ./...

      - name: Run coverage
        run: |
          gotestsum -- -v -race -coverprofile="coverage.out" -covermode=atomic ./...
        env:
          # https://github.com/testcontainers/testcontainers-go/issues/1782
          TESTCONTAINERS_RYUK_DISABLED: true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.3.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: FalcoSuessgott/vault-kubernetes-kms
