name: image_scan
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '40 21 * * 5'

permissions:
  contents: read

jobs:
  build:
    name: Build
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - uses: hadolint/hadolint-action@v3.2.0
        with:
          dockerfile: Dockerfile

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/falcosuessgott/vault-kubernetes-kms:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/falcosuessgott/vault-kubernetes-kms:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
